from dotenv import load_dotenv
import os

load_dotenv()

GOOGLE_CLOUD_CREDENTIALS_JSON = os.getenv('GOOGLE_CLOUD_CREDENTIALS_JSON')
SPREADSHEET_ID = os.getenv('SPREADSHEET_ID')
INVESTIDOR10_EMAIL = os.getenv('INVESTIDOR10_EMAIL')
INVESTIDOR10_PASSWORD = os.getenv('INVESTIDOR10_PASSWORD')
USER_WALLET_ID = os.getenv('USER_WALLET_ID')